[package]
name = "slugterra"
version = "1.0.0"
edition = "2024.alpha" # Using modern 2024 specifications

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.39.2" }

[addresses]
slugterra = "0x0"
